name: CI/CD — NexaCloud API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# ── Job 1 : Qualité ───────────────────────────────────────────────
jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  tests:
    uses: ./.github/workflows/reusable-tests.yml
    with:
      python-version: "3.11"

  # ── Job 2 : Staging ───────────────────────────────────────────────
  staging:
    name: Staging
    runs-on: ubuntu-latest
    needs: [lint, tests]
    environment: staging
    if: github.ref_name == 'main'

    steps:
      - name: Installer les dépendances
        uses: ./.github/workflows/reusable-tests.yml

        with:
          python-version: "3.11"

      - name: Déployer sur Azure App Service (staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "nexacloud-api-staging-23043"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ressources/

  # ── Job 3 : Production ────────────────────────────────────────────
  production:
    name: Production
    runs-on: ubuntu-latest
    needs: staging
    environment: production
    if: github.ref_name == 'main'

    steps:
      - name: Installer les dépendances
        uses: ./.github/workflows/reusable-tests.yml

        with:
          python-version: "3.11"

      - name: Déployer sur Azure App Service (production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "nexacloud-api-23043"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ressources/
